---
# file: roles/basic/tasks/main.yml
- name: Install basic packages
  become: yes
  apt:
    name: "{{ packages}}"
    cache_valid_time: 86400
    update_cache: yes

- name: Get package facts
  package_facts: