---
# file: roles/elastic/tasks/configure.yml
- name: Configure ElasticSearch JVM options
  become: yes
  template:
    src: jvm.options.j2
    dest: "{{ config_dir }}/jvm.options.d/custom.options"
    owner: "{{ elastic_user }}"
    group: "{{ elastic_group }}"
    mode: 0640
  tags: configure

- name: Configure ElasticSearch
  become: yes
  template:
    src: elasticsearch.yml.j2
    dest: "{{ config_dir }}/elasticsearch.yml"
    owner: "{{ elastic_user }}"
    group: "{{ elastic_group }}"
    mode: 0640
  tags: configure

- name: Configure roles
  become: yes
  copy:
    content: "{{ roles | to_nice_yaml }}"
    dest: "{{ config_dir }}/roles.yml"
    owner: "{{ elastic_user }}"
    group: "{{ elastic_group }}"
    mode: 0640
  tags: configure

- name: Add users
  become: yes
  no_log: yes
  shell: |-
    ./elasticsearch-users useradd {{ item.name }} \
    -p {{ item.password }} \
    -r {{ item.roles | join(',') }} || true
  args:
    chdir: "{{ bin_dir }}"
  with_items: "{{ users }}"
  tags: configure

- name: Create cert dir
  become: yes
  file:
    dest: "{{ cert_dir }}"
    state: directory
    owner: "{{ elastic_user }}"
    group: "{{ elastic_user }}"
    mode: 0750
  tags: configure

- block:
    - name: Generate root certificate
      shell: ./elasticsearch-certutil ca --pass "" --out /tmp/ca-{{ cluster_name }}.p12
      args:
        chdir: "{{ bin_dir }}"
        creates: "{{ home_dir }}/.cluster_cert_created"
    - name: Copy certs from node
      fetch:
        src: "/tmp/ca-{{ cluster_name }}.p12"
        dest: /tmp/
        flat: yes
  run_once: yes
  tags: configure

- name: Copy root certs to nodes
  become: yes
  copy:
    src: "/tmp/ca-{{ cluster_name }}.p12"
    dest: /tmp/
    owner: "{{ elastic_user }}"
    group: "{{ elastic_user }}"
    mode: 0644
  tags: configure

- name: Generate certs
  become: yes
  shell: |-
    ./elasticsearch-certutil cert \
    --ca /tmp/ca-{{ cluster_name }}.p12 \
    --ca-pass "" \
    --dns {{ node_name }} \
    --ip {{ ansible_host }} \
    --pass "" \
    --out {{ cert_dir }}/{{ node_name }}.p12 || true
  args:
    chdir: "{{ bin_dir }}"
    creates: "{{ home_dir }}/.node_cert_created"
  tags: configure

- name: Change cert permissions
  become: yes
  file:
    dest: "{{ cert_dir }}/{{ node_name }}.p12"
    owner: "{{ elastic_user }}"
    group: "{{ elastic_user }}"
    state: touch
    mode: 0640
  tags: configure

- name: Delete root certs
  become: yes
  file:
    dest: "/tmp/ca-{{ cluster_name }}.p12"
    state: absent
  tags: configure

- name: Restart EasticSearch
  become: yes
  service:
    name: elasticsearch
    state: restarted
  tags: configure